#! /bin/bash

export PETSC_DIR=/etc/petsc-3.5.3
export PETSC_ARCH=arch-opt
export CavityLibPath=$PWD/CodesForLibrary
export NloptLibPath=/usr/local/lib/
#xdliang/MyLocal/nlopt_0/.libs

cd CodesForLibrary
make clean
rm *.a

cd ../optimization/
make clean
rm *exec *.h
