#! /bin/bash

export PETSC_DIR=/etc/petsc-3.5.3
export PETSC_ARCH=arch-opt
export CavityLibPath=$PWD/CodesForLibrary
export SLEPC_DIR=/etc/slepc-3.5.4
export NloptLibPath=/usr/local/lib/

cd CodesForLibrary
make clean
rm *.a

cd ../optimization/
make clean
rm *exec *.h
