#! /bin/bash

export PETSC_DIR=/home/zlin/MyLocal/petsc-3.6.0
export PETSC_ARCH=arch-opt
export SLEPC_DIR=/home/zlin/MyLocal/slepc-3.6.0
export CavityLibPath=$PWD/CodesForLibrary
export NloptLibPath=/usr/local/lib/

cd CodesForLibrary
bash makelibOPT

cd ../optimization/
ln -s ../CodesForLibrary/libOPT.h ./
make clean 
make
make clean

