#! /bin/bash

export PETSC_DIR=/etc/petsc-3.5.3
export PETSC_ARCH=arch-opt
export SLEPC_DIR=/etc/slepc-3.5.4
export CavityLibPath=~/share/Opt_Cartesian/CodesForLibrary
export NloptLibPath=/usr/local/lib/

cd CodesForLibrary
bash makelibOPT

cd ../optimization/
make clean 
make
make clean

