#! /bin/bash

export PETSC_DIR=/opt/local/petsc-3.6.3
export PETSC_ARCH=arch-opt
export SLEPC_DIR=/opt/local/slepc-3.6.2
export CavityLibPath=~/Opt_Cartesian/CodesForLibrary
export NloptLibPath=/usr/local/lib/

cd CodesForLibrary
bash makelibOPT

cd ../optimization/
make clean 
make
make clean

